name: ai-mail-assistant
channels:
  - pytorch         
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - flask
  - joblib
  - transformers
  - pip

  - pytorch
  - cpuonly

  - pip:
      - kagglehub
