name: ai-mail-assistant
channels:
  - conda-forge      
  - defaults
dependencies:
  - python=3.12      
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - pip              
  - pip:
      - kagglehub
